#! /bin/bash
# config file for the nibs-cp project

# you are in the drcmr cluster. But we are double checking

if [[ "$HOSTNAME" != *.drcmr ]]; then
    echo "Error: This script is intended to be run on the drcmr cluster."
    exit 1
else
    echo "You are in the drcmr cluster. Proceeding with configuration."
    
    ########################
    ## PATHS
    ########################

    # raw inputs
    NIBS_CP_XNAT="/mnt/xnat/NIBS-CP"  
    NIBS_CP_PROJ="/mnt/projects/NIBS-CP" 
    # raw outputs
    NIBS_CP_BIDS="/mnt/projects/NIBS-CP_BIDS"

    # diffusion pipeline
    DIFF_PIPELINE_DIR="/mnt/projects/NIBS-CP/nibs-cp-diff"
    DIFF_SRC_DIR="$DIFF_PIPELINE_DIR/src"
    DIFF_CONFIG_DIR="$DIFF_PIPELINE_DIR/config"

    # Binaries
    PYTHON_BIN="$DIFF_PIPELINE_DIR/env/bin/python"


    ########################
    ## PARAMETERS
    ########################



fi

